'use client';

import { zodResolver } from '@hookform/resolvers/zod';
import { ArrowLeft, Loader2, Save } from 'lucide-react';
import Link from 'next/link'; import { useRouter } from 'next/navigation'; import { useEffect, useState } from 'react'; import { useForm } from 'react-hook-form';
import { createCategoryAction, updateCategoryAction } from '@/app/admin/(panel)/categorias/actions/category-actions';
import { CategoryImageUploader } from './category-image-uploader';
import { categoryFormSchema, type CategoryFormInput, type CategoryFormValues } from '@/lib/categories/schema'; import { createCategorySlug } from '@/lib/categories/slug';

const empty: CategoryFormValues = { name: '', slug: '', description: '', sortOrder: 0, isActive: true, isFeatured: false, mainImage: null, desktopBanner: null, mobileBanner: null, seoTitle: '', seoDescription: '', seoKeywords: '', imageAlt: '', canonicalUrl: '' };
const inputClass = 'mt-2 h-11 w-full rounded-xl border border-slate-200 px-3 text-sm outline-none focus:border-green-600 focus:ring-4 focus:ring-green-100';
export function CategoryForm({ mode = 'create', categoryId, initialValues }: { mode?: 'create' | 'edit'; categoryId?: string; initialValues?: CategoryFormValues }) {
  const router = useRouter(); const [saving, setSaving] = useState(false); const [slugEdited, setSlugEdited] = useState(mode === 'edit'); const [notice, setNotice] = useState<{ ok: boolean; text: string } | null>(null);
  const { register, handleSubmit, watch, setValue, formState: { errors } } = useForm<CategoryFormInput, unknown, CategoryFormValues>({ resolver: zodResolver(categoryFormSchema), defaultValues: initialValues ?? empty });
  const name = watch('name'); useEffect(() => { if (!slugEdited) setValue('slug', createCategorySlug(name)); }, [name, setValue, slugEdited]);
  async function submit(values: CategoryFormValues) { setSaving(true); setNotice(null); const result = mode === 'edit' && categoryId ? await updateCategoryAction(categoryId, values) : await createCategoryAction(values); setSaving(false); setNotice({ ok: result.success, text: result.message }); if (result.success) { router.refresh(); if (mode === 'create' && result.categoryId) router.replace(`/admin/categorias/${result.categoryId}/editar`); } }
  const Field = ({ label, error, children }: { label: string; error?: string; children: React.ReactNode }) => <label className="block text-sm font-medium text-slate-700">{label}{children}{error && <span className="mt-1 block text-xs text-red-600">{error}</span>}</label>;
  return <form onSubmit={handleSubmit(submit)} className="mx-auto max-w-[1100px]">
    <div className="mb-7 flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><Link href="/admin/categorias" className="inline-flex items-center gap-2 text-sm text-slate-500"><ArrowLeft className="h-4 w-4" />Volver a categorías</Link><h1 className="mt-4 text-3xl font-semibold">{mode === 'edit' ? 'Editar categoría' : 'Nueva categoría'}</h1><p className="mt-2 text-sm text-slate-500">Administrá su presentación, publicación y SEO.</p></div><button disabled={saving} className="inline-flex min-h-11 items-center justify-center gap-2 rounded-xl bg-green-700 px-5 text-sm font-semibold text-white disabled:opacity-60">{saving ? <Loader2 className="h-4 w-4 animate-spin" /> : <Save className="h-4 w-4" />}{saving ? 'Guardando...' : 'Guardar categoría'}</button></div>
    {notice && <div role={notice.ok ? 'status' : 'alert'} className={`mb-5 rounded-xl border p-4 text-sm ${notice.ok ? 'border-green-200 bg-green-50 text-green-800' : 'border-red-200 bg-red-50 text-red-700'}`}>{notice.text}</div>}
    <div className="space-y-6"><section className="rounded-2xl border bg-white p-5 shadow-sm"><h2 className="text-lg font-semibold">Información básica</h2><div className="mt-5 grid gap-5 md:grid-cols-2"><Field label="Nombre" error={errors.name?.message}><input {...register('name')} className={inputClass} /></Field><Field label="Slug" error={errors.slug?.message}><input {...register('slug', { onChange: () => setSlugEdited(true) })} className={inputClass} /></Field><Field label="Orden" error={errors.sortOrder?.message}><input type="number" min="0" {...register('sortOrder', { valueAsNumber: true })} className={inputClass} /></Field><div className="flex items-center gap-6 pt-7"><label className="flex gap-2 text-sm"><input type="checkbox" {...register('isActive')} /> Activa</label><label className="flex gap-2 text-sm"><input type="checkbox" {...register('isFeatured')} /> Destacada</label></div><div className="md:col-span-2"><Field label="Descripción" error={errors.description?.message}><textarea {...register('description')} rows={5} className={`${inputClass} h-auto py-3`} /></Field></div></div></section>
    <section className="rounded-2xl border bg-white p-5 shadow-sm"><h2 className="text-lg font-semibold">Imágenes</h2><div className="mt-5 grid gap-6 md:grid-cols-2"><CategoryImageUploader label="Imagen principal" categoryName={name} value={watch('mainImage')} onChange={(v) => setValue('mainImage', v, { shouldValidate: true })} /><CategoryImageUploader label="Banner Desktop" aspect="desktop" categoryName={name} value={watch('desktopBanner')} onChange={(v) => setValue('desktopBanner', v, { shouldValidate: true })} /><CategoryImageUploader label="Banner Mobile" aspect="mobile" categoryName={name} value={watch('mobileBanner')} onChange={(v) => setValue('mobileBanner', v, { shouldValidate: true })} /></div></section>
    <section className="rounded-2xl border bg-white p-5 shadow-sm"><h2 className="text-lg font-semibold">SEO</h2><div className="mt-5 grid gap-5 md:grid-cols-2"><Field label="Título SEO" error={errors.seoTitle?.message}><input {...register('seoTitle')} className={inputClass} /></Field><Field label="Texto alternativo" error={errors.imageAlt?.message}><input {...register('imageAlt')} className={inputClass} /></Field><div className="md:col-span-2"><Field label="Descripción SEO" error={errors.seoDescription?.message}><textarea {...register('seoDescription')} rows={3} className={`${inputClass} h-auto py-3`} /></Field></div><Field label="Palabras clave (separadas por comas)" error={errors.seoKeywords?.message}><input {...register('seoKeywords')} className={inputClass} /></Field><Field label="URL canónica" error={errors.canonicalUrl?.message}><input {...register('canonicalUrl')} className={inputClass} /></Field></div></section></div>
  </form>;
}
